---
title: "Choose PCs"
author: "Briana Mittleman"
date: "5/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(reshape2)
```

Concatinate qqnorm res:  

```{bash,eval=F}
less APApeak_Phenotype_GeneLocAnno.Total.5perc.fc.gz.qqnorm_chr*.gz > APApeak_Phenotype_GeneLocAnno.Total.5perc.fc.gz.qqnorm.allChrom
less APApeak_Phenotype_GeneLocAnno.Nuclear.5perc.fc.gz.qqnorm_chr*.gz > APApeak_Phenotype_GeneLocAnno.Nuclear.5perc.fc.gz.qqnorm.allChrom
```

```{r}
totalqqnorm=read.table("../data/phenotype_5perc/APApeak_Phenotype_GeneLocAnno.Total.5perc.fc.gz.qqnorm.allChrom", col.names = c('Chr',	'start',	'end',	'ID',	'NA18486',	'NA18498',	'NA18499',	'NA18501',	'NA18502',	'NA18504', 'NA18505',	'NA18508',	'NA18510',	'NA18511',	'NA18516',	'NA18519',	'NA18520',	'NA18522',	'NA18852', 'NA18853',	'NA18855',	'NA18856',	'NA18858',	'NA18861',	'NA18862',	'NA18870',	'NA18907',	'NA18909',	'NA18912', 'NA18913',	'NA18916',	'NA19092',	'NA19093',	'NA19101',	'NA19119',	'NA19130',	'NA19131',	'NA19137','NA19138',	'NA19140',	'NA19141',	'NA19144',	'NA19152',	'NA19153',	'NA19160',	'NA19171',	'NA19193',	'NA19200','NA19207',	'NA19209',	'NA19210',	'NA19223',	'NA19225',	'NA19238',	'NA19239',	'NA19257') )

totalqqnorm_matrix=as.matrix(totalqqnorm %>% select(-Chr, -start, -end, -ID))
```


RUn PCA:

```{r}
pca_tot_peak=prcomp(totalqqnorm_matrix, center=T,scale=T)
pca_tot_df=as.data.frame(pca_tot_peak$rotation) %>% rownames_to_column(var="lib") %>% select(1:11)

pca_tot_df_fix=bind_cols(line=pca_tot_df[,dim(pca_tot_df)[[2]]],pca_tot_df[,3:dim(pca_tot_df)[[2]]-1])
```

Variance explained:

```{r}
eigs_tot <- pca_tot_peak$sdev^2
proportion_tot = eigs_tot/sum(eigs_tot)

plot(proportion_tot)
```

```{r}
nuclearqqnorm=read.table("../data/phenotype_5perc/APApeak_Phenotype_GeneLocAnno.Nuclear.5perc.fc.gz.qqnorm.allChrom", col.names = c('Chr',	'start',	'end',	'ID',	'NA18486',	'NA18498',	'NA18499',	'NA18501',	'NA18502',	'NA18504', 'NA18505',	'NA18508',	'NA18510',	'NA18511',	'NA18516',	'NA18519',	'NA18520',	'NA18522',	'NA18852', 'NA18853',	'NA18855',	'NA18856',	'NA18858',	'NA18861',	'NA18862',	'NA18870',	'NA18907',	'NA18909',	'NA18912', 'NA18913',	'NA18916',	'NA19092',	'NA19093',	'NA19101',	'NA19119',	'NA19130',	'NA19131',	'NA19137','NA19138',	'NA19140',	'NA19141',	'NA19144',	'NA19152',	'NA19153',	'NA19160',	'NA19171',	'NA19193',	'NA19200','NA19207',	'NA19209',	'NA19210',	'NA19223',	'NA19225',	'NA19238',	'NA19239',	'NA19257'))

nuclearqqnorm_matrix=as.matrix(nuclearqqnorm %>% select(-Chr, -start, -end, -ID))
```


```{r}
pca_nuc_peak=prcomp(nuclearqqnorm_matrix, center=T,scale=T)
pca_nuc_df=as.data.frame(pca_nuc_peak$rotation) %>% rownames_to_column(var="lib") %>% select(1:11)

pca_nuc_df_fix=bind_cols(line=pca_nuc_df[,dim(pca_nuc_df)[[2]]],pca_nuc_df[,3:dim(pca_nuc_df)[[2]]-1])
```


Variance explained:

```{r}
eigs_nuc <- pca_nuc_peak$sdev^2
proportion_nuc = eigs_nuc/sum(eigs_nuc)

plot(proportion_nuc)
```


Plot together:

```{r}
both_prop=as.data.frame(cbind(PCs=seq(1,54,1),Total=proportion_tot,Nuclear=proportion_nuc))

both_prop_melt=melt(both_prop, id.var=c("PCs"), variable.name="Fraction",value.name = "VariationExplained" )


```


```{r}
ggplot(both_prop_melt, aes(x=PCs, y=VariationExplained,group=Fraction, color=Fraction)) + geom_line() + geom_vline(xintercept = 6, col="red") + annotate("text", label="6 PCs", x=10, y=.1) + labs(title="Proportion of variance explained \nin PCA on normalized APA usage")
```


```{r}
both_prop_melt_filt=both_prop_melt %>% filter(PCs<10)

ggplot(both_prop_melt_filt, aes(x=PCs, y=VariationExplained,group=Fraction, color=Fraction)) + geom_line() + geom_vline(xintercept = 4, col="red") + annotate("text", label="4 PCs", x=5, y=.1) + labs(title="Proportion of variance explained \nin PCA on normalized APA usage")
```
WHich factors correlate with PCs:

```{r}
metadata=read.table("../data/MetaDataSequencing.txt", stringsAsFactors = F, header = T)
metadata_tot=metadata %>% filter(fraction=="total") %>% select(batch,Sex, alive_avg, undiluted_avg,ratio260_280)
metadata_nuc=metadata %>% filter(fraction=="nuclear") %>% select(batch,Sex, alive_avg, undiluted_avg,ratio260_280)
```

Function from Ben 

```{r}
covariate_pc_pve_heatmap <- function(pc_df, covariate_df, title) {
  # Load in data
  pcs <- pc_df
  #pcs=pca_tot_df
  covs <- covariate_df
  #covs=metadata_tot

# Remove unimportant columns
  pcs <- as.matrix(pcs[,2:dim(pcs)[[2]]])
  covs <- data.frame(as.matrix(covs[,1:dim(covs)[[2]]]))

  # Initialize PVE heatmap
  pve_map <- matrix(0, dim(covs)[2], dim(pcs)[2])
  colnames(pve_map) <- colnames(pcs)
  rownames(pve_map) <- colnames(covs)

  # Loop through each PC, COV Pair and take correlation
  num_pcs <- dim(pcs)[2]
  num_covs <- dim(covs)[2]
  for (num_pc in 1:num_pcs) {
    for (num_cov in 1:num_covs) {
      pc_vec <- pcs[,num_pc]
      cov_vec <- covs[,num_cov]
      lin_model <- lm(pc_vec ~ cov_vec)
      pve_map[num_cov, num_pc] <- summary(lin_model)$adj.r.squared
      if (pve_map[num_cov, num_pc] <0){pve_map[num_cov, num_pc]=0}
    }
  }
  pve_map
  ord <- hclust( dist(scale(pve_map), method = "euclidean"), method = "ward.D" )$order

  melted_mat <- melt(pve_map)
  colnames(melted_mat) <- c("Covariate", "PC","PVE")

  #  Use factors to represent covariate and pc name
  melted_mat$Covariate <- factor(melted_mat$Covariate, levels = rownames(pve_map)[ord])
  melted_mat$PC <- factor(melted_mat$PC)
  if (dim(pcs)[2] == 10) {
    levels(melted_mat$PC) <- c(levels(melted_mat$PC)[1],levels(melted_mat$PC)[3:10],levels(melted_mat$PC)[2])
  }
  if (dim(pcs)[2] == 21) {
    levels(melted_mat$PC) <- c(levels(melted_mat$PC)[1],levels(melted_mat$PC)[12],levels(melted_mat$PC)[15:21],levels(melted_mat$PC)[2:11], levels(melted_mat$PC)[13:14])
  }

  #  PLOT!
  heatmap <- ggplot(data=melted_mat, aes(x=Covariate, y=PC)) + geom_tile(aes(fill=PVE)) + scale_fill_gradient2(midpoint=-.05, guide="colorbar")
  heatmap <- heatmap + theme(text = element_text(size=14), panel.background = element_blank(), axis.text.x = element_text(angle = 90, vjust=.5))
  heatmap <- heatmap + labs(y="latent factor", title=title)

  # Save File
  return(heatmap)
}
```


```{r}
covariate_pc_pve_heatmap(pca_tot_df,metadata_tot, title="Total PCs")

covariate_pc_pve_heatmap(pca_nuc_df,metadata_nuc, title="Nuclear PCs")

```

