---
title: "Correlation between Individuals"
author: "Briana Mittleman"
date: "4/24/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
In this analysis I will look at correlations heatmaps for the counts of all of the inidividuals. 

```{r}
library(tidyverse)
library(workflowr)
library(reshape2)
library(gplots)
library(gdata)
```

Load metadata:  

```{r}
metadata=read.table("../data/MetaDataSequencing.txt",header = T)
meta_T=metadata %>% filter(grepl("T", Sample_ID)) %>% mutate(samp=paste("X", Sample_ID, sep=""))
meta_N=metadata %>% filter(grepl("N", Sample_ID)) %>%  mutate(samp=paste("X", Sample_ID, sep=""))
```


##Correlation in counts:  
###Total  

```{r}
totCount=read.table("../data/peakCoverage/APAPeaks.ALLChrom.Filtered.Named.GeneLocAnnoPARSED.Total.Quant.Fixed.fc", stringsAsFactors = F,header=T) %>% select(-Geneid, -Chr, -Start, -End, -Strand, -Length)
```

Correlation: 

```{r}
totCount_corr= round(cor(totCount),2)

totCount_corr_melt=melt(totCount_corr)

```

Use heatmap2.  

```{r}

meta_TBatch=meta_T %>% select(samp,batch)

target=colnames(totCount_corr)
meta_TBatch$samp <- reorder.factor(meta_TBatch$samp, new.order=target)
meta_TBatch_order=meta_TBatch %>% arrange(samp)

meta_TBatch_order = meta_TBatch_order %>% mutate(color=ifelse(batch=="1", "green", ifelse(batch=="2", "blue", ifelse(batch=="3", "purple", "pink"))))


heatmap.2(as.matrix(totCount_corr),trace="none", dendrogram =c("col"), ColSideColors =meta_TBatch_order$color, key=T)
```



###Nuclear  


```{r}
nucCount=read.table("../data/peakCoverage/APAPeaks.ALLChrom.Filtered.Named.GeneLocAnnoPARSED.Nuclear.Quant.Fixed.fc", stringsAsFactors = F,header=T) %>% select(-Geneid, -Chr, -Start, -End, -Strand, -Length)
```

Correlation: 

```{r}
nucCount_corr= round(cor(nucCount),2)

nucCount_corr_melt=melt(nucCount_corr)

```

```{r}
meta_NBatch=meta_N %>% select(samp,batch)
target=colnames(nucCount_corr)
meta_NBatch$samp <- reorder.factor(meta_NBatch$samp, new.order=target)
meta_NBatch_order=meta_NBatch %>% arrange(samp)

meta_NBatch_order = meta_NBatch_order %>% mutate(color=ifelse(batch=="1", "green", ifelse(batch=="2", "blue", ifelse(batch=="3", "purple", "pink"))))


heatmap.2(as.matrix(nucCount_corr),trace="none", dendrogram =c("col"), ColSideColors =meta_NBatch_order$color, key=T)
```


##Correlation in Usage  

###Total  

```{r}
totUsage=read.table("../data/phenotype_5perc/APApeak_Phenotype_GeneLocAnno.Total.5perc.CountsNumeric", stringsAsFactors = F,header=F, col.names = colnames(totCount)) 
```

Correlation: 

```{r}
totUsage_corr= round(cor(totUsage),2)

totUsage_corr_melt=melt(totUsage_corr)

```

Plot heatmap:
```{r}
ggplot(data = totUsage_corr_melt, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile() +theme(axis.text.x = element_text(angle = 90))
```
###Nuclear  


```{r}
nucUsage=read.table("../data/phenotype_5perc/APApeak_Phenotype_GeneLocAnno.Nuclear.5perc.CountsNumeric", stringsAsFactors = F,header=F, col.names = colnames(nucCount)) 
```

Correlation: 

```{r}
nucUsage_corr= round(cor(nucUsage),2)

nucUsage_corr_melt=melt(nucUsage_corr)

```

Plot heatmap:

```{r}
ggplot(data = nucUsage_corr_melt, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile() +theme(axis.text.x = element_text(angle = 90))
```
