---
title: "RiboQTL QQplot"
author: "Briana Mittleman"
date: "2/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In the paper I have qqPlots where I took the apaQTL data and subset it by QTL sets. I never did this for riboQTLs. I will get the riboQTLs from Battle et al and remake the plot including these. 

```{r}
library(tidyverse)

```


```{r}
geneNames=read.table("../../genome_anotation_data/ensemble_to_genename.txt", sep="\t", col.names = c('ENSG', 'GeneName', 'source' ),stringsAsFactors = F, header = T)

riboRes=read.table("../data/Battle_pQTL/riboQTLs_battle.txt", header = T,stringsAsFactors = F) %>% inner_join(geneNames,by="ENSG") 

exPe=read.table("../data/Li_eQTLs/explainedEgenes.txt", col.names = "GeneName")
UexPe=read.table("../data/Li_eQTLs/UnexplainedEgenes.txt",col.names = "GeneName")

allE=exPe %>% full_join(UexPe,by="GeneName")

riboRes$bh=p.adjust(riboRes$perm.p.values, method="fdr")

riboRes_sig= riboRes %>% filter(-log10(bh)>=1)

riboGenes=riboRes_sig %>% select(GeneName) %>% anti_join(allE)




write.table(riboGenes, file="../data/Battle_pQTL/RiboQTLGeneNames.txt", row.names = F, col.names = F, quote = F, sep="\t")
```


```{bash,eval=F}
mkdir ../data/ApaByRgene

python subsetpermAPAwithGenelist.py ../data/Battle_pQTL/RiboQTLGeneNames.txt Nuclear ../data/ApaByRgene/NuclearApaRGenes.txt

python subsetpermAPAwithGenelist.py ../data/Battle_pQTL/RiboQTLGeneNames.txt Total ../data/ApaByRgene/TotalApaRGenes.txt

python subsetAPAnotEorR.py Nuclear ../data/ApaByRgene/NotRorE_nuclear.txt
python subsetAPAnotEorR.py Total ../data/ApaByRgene/NotRorE_total.txt
```



```{r}
tot.notEorR=read.table("../data/ApaByRgene/NotRorE_total.txt",stringsAsFactors = F,col.names = c("pid", "nvar", "shape1", "shape2", "dummy", "sid", "dist", "npval", "slope", "ppval", "bpval"))
tot.RS=read.table("../data/ApaByRgene/TotalApaRGenes.txt",stringsAsFactors = F,col.names = c("pid", "nvar", "shape1", "shape2", "dummy", "sid", "dist", "npval", "slope", "ppval", "bpval"))
tot.ES=read.table("../data/ApaByPgene/TotalApaESGenes.txt",stringsAsFactors = F, col.names = c("pid", "nvar", "shape1", "shape2", "dummy", "sid", "dist", "npval", "slope", "ppval", "bpval") )
tot.ex=read.table("../data/ApaByEgene/TotalApaexplainedeGenes.txt",stringsAsFactors = F,col.names = c("pid", "nvar", "shape1", "shape2", "dummy", "sid", "dist", "npval", "slope", "ppval", "bpval"))
tot.un=read.table("../data/ApaByEgene/TotalApaUnexplainedeGenes.txt",stringsAsFactors = F, col.names = c("pid", "nvar", "shape1", "shape2", "dummy", "sid", "dist", "npval", "slope", "ppval", "bpval") )

tot_allE=as.data.frame(rbind(tot.ex,tot.un))
tot.RS=na.omit(tot.RS)
tot.notEorR=na.omit(tot.notEorR)
tot.ES=na.omit(tot.ES)
tot.un=na.omit(tot.un)
```


```{r}
qqplot(-log10(runif(nrow(tot.notEorR))), -log10(tot.notEorR$bpval), xlab="-log10(Uniform)", ylab="-log10(beta pval)", main="Total Apa")
points(sort(-log10(runif(nrow(tot.RS)))), sort(-log10(tot.RS$bpval)),col= alpha("Red"))
points(sort(-log10(runif(nrow(tot_allE)))), sort(-log10(tot_allE$bpval)),col= alpha("blue"))
abline(0,1)

legend("topleft", legend=c("Neither eGenes nor rGenes", "rGenes", "eGenes"),col=c("black", "red","blue"), pch=16,bty = 'n')
```
```{r}
wilcox.test(tot.RS$bpval,tot.notEorR$bpval,alternative="less")
wilcox.test(tot_allE$bpval,tot.notEorR$bpval,alternative="less")
wilcox.test(tot.RS$bpval,tot_allE$bpval,alternative="less")
```


```{r}
nuc.notEorR=read.table("../data/ApaByRgene/NotRorE_nuclear.txt",stringsAsFactors = F,col.names = c("pid", "nvar", "shape1", "shape2", "dummy", "sid", "dist", "npval", "slope", "ppval", "bpval"))
nuc.RS=read.table("../data/ApaByRgene/NuclearApaRGenes.txt",stringsAsFactors = F,col.names = c("pid", "nvar", "shape1", "shape2", "dummy", "sid", "dist", "npval", "slope", "ppval", "bpval"))
nuc.P=read.table("../data/ApaByPgene/NuclearApaPSGenes.txt",stringsAsFactors = F,col.names = c("pid", "nvar", "shape1", "shape2", "dummy", "sid", "dist", "npval", "slope", "ppval", "bpval"))
nuc.ES=read.table("../data/ApaByPgene/NuclearApaESGenes.txt",stringsAsFactors = F, col.names = c("pid", "nvar", "shape1", "shape2", "dummy", "sid", "dist", "npval", "slope", "ppval", "bpval") )
nuc.ex=read.table("../data/ApaByEgene/NuclearApaexplainedeGenes.txt",stringsAsFactors = F,col.names = c("pid", "nvar", "shape1", "shape2", "dummy", "sid", "dist", "npval", "slope", "ppval", "bpval"))
nuc.un=read.table("../data/ApaByEgene/NuclearApaUnexplainedeGenes.txt",stringsAsFactors = F, col.names = c("pid", "nvar", "shape1", "shape2", "dummy", "sid", "dist", "npval", "slope", "ppval", "bpval") )

nuc.un=na.omit(nuc.un)
nuc.RS=na.omit(nuc.RS)
#nuc.notERorP=na.omit(nuc.notERorP)
nuc.P=na.omit(nuc.P)
nuc.notEorR=na.omit(nuc.notEorR)
nuc.ES=na.omit(nuc.ES)
nuc_allE=as.data.frame(rbind(nuc.ex,nuc.un))
```

```{r}
qqplot(-log10(runif(nrow(nuc.notEorR))), -log10(nuc.notEorR$bpval), xlab="-log10(Uniform)", ylab="-log10(beta pval)", main="Nuclear Apa")
points(sort(-log10(runif(nrow(nuc.RS)))), sort(-log10(nuc.RS$bpval)),col= alpha("Red"))
points(sort(-log10(runif(nrow(nuc_allE)))), sort(-log10(nuc_allE$bpval)),col= alpha("blue"))
abline(0,1)

legend("topleft", legend=c("Neither eGenes nor rGenes", "rGenes", "eGenes"),col=c("black", "red","blue","green"), pch=16,bty = 'n')
```
```{r}
wilcox.test(nuc.RS$bpval,nuc.notEorR$bpval,alternative="less")
wilcox.test(nuc_allE$bpval,nuc.notEorR$bpval,alternative="less")
wilcox.test(nuc.RS$bpval,nuc_allE$bpval,alternative="less")
```


```{r figure4ribo, include=FALSE, dev="pdf", fig.height=6, fig.width=10, crop=FALSE}

qqplot(-log10(runif(nrow(nuc.notEorR))), -log10(nuc.notEorR$bpval), xlab="-log10(Uniform)", ylab="-log10(beta pval)", main="Nuclear Apa")
points(sort(-log10(runif(nrow(nuc.RS)))), sort(-log10(nuc.RS$bpval)),col= alpha("Red"))
points(sort(-log10(runif(nrow(nuc_allE)))), sort(-log10(nuc_allE$bpval)),col= alpha("blue"))
abline(0,1)

legend("topleft", legend=c("Neither eGenes nor rGenes", "rGenes", "eGenes"),col=c("black", "red","blue","green"), pch=16,bty = 'n')

```


No QTL at all. 


```{bash,eval=F}
python subsetNootherQTL.py Nuclear ../data/ApaByRgene/NotANY_nuclear.txt
```



```{r}
notany_nuc=read.table("../data/ApaByRgene/NotANY_nuclear.txt",stringsAsFactors = F, col.names = c("pid", "nvar", "shape1", "shape2", "dummy", "sid", "dist", "npval", "slope", "ppval", "bpval") )
notany_nuc=na.omit(notany_nuc)
```

```{r}
qqplot(-log10(runif(nrow(notany_nuc))), -log10(notany_nuc$bpval), xlab="-log10(Uniform)", ylab="-log10(beta pval)", main="Nuclear Apa")
points(sort(-log10(runif(nrow(nuc_allE)))), sort(-log10(nuc_allE$bpval)),col= alpha("blue"))
points(sort(-log10(runif(nrow(nuc.RS)))), sort(-log10(nuc.RS$bpval)),col= alpha("Red"))
points(sort(-log10(runif(nrow(nuc.P)))), sort(-log10(nuc.P$bpval)),col= alpha("Green"))
abline(0,1)

legend("topleft", legend=c("No other QTL","rGenes", "pGenes","eGenes"),col=c("black", "red","Green","blue"), pch=16,bty = 'n')

```
```{r figure4riboandP, include=FALSE, dev="pdf", fig.height=6, fig.width=10, crop=FALSE}
qqplot(-log10(runif(nrow(notany_nuc))), -log10(notany_nuc$bpval), xlab="-log10(Uniform)", ylab="-log10(beta pval)", main="Nuclear Apa")
points(sort(-log10(runif(nrow(nuc_allE)))), sort(-log10(nuc_allE$bpval)),col= alpha("blue"))
points(sort(-log10(runif(nrow(nuc.RS)))), sort(-log10(nuc.RS$bpval)),col= alpha("Red"))
points(sort(-log10(runif(nrow(nuc.P)))), sort(-log10(nuc.P$bpval)),col= alpha("Green"))
abline(0,1)

legend("topleft", legend=c("No other QTL","rGenes", "pGenes","eGenes"),col=c("black", "red","Green","blue"), pch=16,bty = 'n')

```
